[package]
name = "synpixel/data-store-bucket"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
authors = ["synpixel"]
realm = "server"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
